<?php

/**
 * @file
 * Primary module hooks for LocalGov KeyNav module.
 */

function localgov_keynav_preprocess_page(&$variables) {

  // Correct way to get the module path in Drupal 8+.
  $module_path = \Drupal::service('extension.path.resolver')->getPath('module', 'localgov_keynav');
  dump($module_path);
  $settings = [
    'modulePath' => $module_path,
    'marky' => 'marky',
  ];

  // Attach the settings to the page.
  $variables['#attached']['drupalSettings']['localgovKeyNav'] = $settings;

  // Add the keynav library to the page.
  $variables['#attached']['library'][] = 'localgov_keynav/keynav';
}
