<?php

/**
 * @file
 * Primary module hooks for LocalGov KeyNav module.
 */

/**
 * Implements hook_preprocess_page().
 */
function localgov_keynav_preprocess_page(&$variables) {

  // Get the current user.
  $current_user = \Drupal::currentUser();

  // Check if the user has the 'use keynav' permission.
  if ($current_user->hasPermission('Use LocalGov keynav')) {

    $module_path = \Drupal::service('extension.path.resolver')->getPath('module', 'localgov_keynav');
    $settings = [
      'modulePath' => $module_path,
    ];

    // Attach the settings to the page.
    $variables['#attached']['drupalSettings']['localgovKeyNav'] = $settings;

    // Add the keynav library to the page.
    $variables['#attached']['library'][] = 'localgov_keynav/keynav';
  }
}
